=== BraedonBarham/BraedonBarham.github.io/HotelValidator/Hotels.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="https://BraedonBarham.github.io/Hotels.xsd" targetNamespace="https://BraedonBarham.github.io/Hotels.xsd" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xsd:annotation>
		<xsd:documentation xml:lang="en"> Distributed Software Development Course Example </xsd:documentation>
	</xsd:annotation>
	<xsd:element name="Hotels" type="HotelsType"/>
	<xsd:complexType name="HotelsType">
		<xsd:sequence>
			<xsd:element name="Hotel" type="HotelDetails" minOccurs="1" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="HotelDetails">
		<xsd:sequence>
			<xsd:element name="Name" type="xsd:string" minOccurs="1" maxOccurs="1"/>
			<xsd:element name="Phone" type="xsd:string" minOccurs="1" maxOccurs="unbounded"/>
			<xsd:element name="Address" type="AddressDetails" minOccurs="1" maxOccurs="1"/>
		</xsd:sequence>
		<xsd:attribute name="_Rating" type=" xsd:decimal" use="optional"/>
	</xsd:complexType>
	<xsd:complexType name="AddressDetails">
		<xsd:sequence>
			<xsd:element name="Number" type="xsd:int" minOccurs="1" />
			<xsd:element name="Street" type="xsd:string" minOccurs="1"/>
			<xsd:element name="City" type="xsd:string" minOccurs="1" />
			<xsd:element name="State" type="xsd:string" minOccurs="1" />
			<xsd:element name="Zip" type="xsd:int" minOccurs="1" />
		</xsd:sequence>
		<xsd:attribute name="_NearstAirport" type="xsd:string" use="required" />
	</xsd:complexType>
</xsd:schema>

=== BraedonBarham/BraedonBarham.github.io/Hotels.xml
<Hotels xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="https://BraedonBarham.github.io/Hotels.xsd" xsi:schemaLocation="https://BraedonBarham.github.io/Hotels.xsd https://BraedonBarham.github.io/Hotels.xsd">
	<Hotel Rating="4.2">
		<Name>Westin</Name>
		<Phone>480-968-8885</Phone>
		<Phone>800-937-8461</Phone>
		<Address NearstAirport="Phoenix Sky Harbor">
			<Number>11</Number>
			<Street>E.7th St</Street>
			<City>Tempe</City>
			<State>AZ</State>
			<Zip>85281</Zip>
		</Address>
	</Hotel>
	<Hotel Rating="4.5">
		<Name>Omni Hotels at ASU, Tempe</Name>
		<Phone>602-794-8600</Phone>
		<Address NearstAirport="Phoenix Sky Harbor">
			<Number>7</Number>
			<Street>E University Dr</Street>
			<City>Tempe</City>
			<State>AZ</State>
			<Zip>85281</Zip>
		</Address>
	</Hotel>
	<Hotel>
		<Name>DoubleTree by Hilton Hotel</Name>
		<Phone>480-967-1441</Phone>
		<Address NearstAirport="Phoenix Sky Harbor">
			<Number>2100</Number>
			<Street>S Priest Dr</Street>
			<City>Tempe</City>
			<State>AZ</State>
			<Zip>85282</Zip>
		</Address>
	</Hotel>
	<Hotel Rating="4.5">
		<Name>Hyatt Place Tempe</Name>
		<Phone>480-207-1578</Phone>
		<Address NearstAirport="Phoenix Sky Harbor">
			<Number>601</Number>
			<Street>E 6th St</Street>
			<City>Tempe</City>
			<State>AZ</State>
			<Zip>85281</Zip>
		</Address>
	</Hotel>
	<Hotel>
		<Name>The Phoenician</Name>
		<Phone>480-941-8200</Phone>
		<Address NearstAirport="Phoenix Sky Harbor">
			<Number>6000 </Number>
			<Street>E Camelback Rd</Street>
			<City>Scottsdale</City>
			<State>AZ</State>
			<Zip>85251</Zip>
		</Address>
	</Hotel>
	<Hotel Rating="4.6">
		<Name>Arizona Biltmore</Name>
		<Phone>602-955-6600</Phone>
		<Phone>602-955-6601</Phone>
		<Address NearstAirport="Phoenix Sky Harbor">
			<Number>2400 </Number>
			<Street>E Missouri Ave</Street>
			<City>Phoenix</City>
			<State>AZ</State>
			<Zip>85016</Zip>
		</Address>
	</Hotel>
	<Hotel>
		<Name>Renaissance Phoenix Downtown Hotel</Name>
		<Phone>602-333-0000</Phone>
		<Address NearstAirport="Phoenix Sky Harbor">
			<Number>100</Number>
			<Street>N 1st St</Street>
			<City>Phoenix</City>
			<State>AZ</State>
			<Zip>85004</Zip>
		</Address>
	</Hotel>
	<Hotel Rating="4.6">
		<Name>Omni Scottsdale Resort &amp; Spa at Montelucia</Name>
		<Phone>480-627-3200</Phone>
		<Address NearstAirport="Phoenix Sky Harbor">
			<Number>4949</Number>
			<Street>E Lincoln Dr</Street>
			<City>Scottsdale</City>
			<State>AZ</State>
			<Zip>85253</Zip>
		</Address>
	</Hotel>
	<Hotel Rating="4.6">
		<Name>Encore Las Vegas</Name>
		<Phone>702-770-7000</Phone>
		<Phone>702-770-7010</Phone>
		<Address NearstAirport="Las Vegas Airport">
			<Number>3121</Number>
			<Street>S Las Vegas Blvd</Street>
			<City>Las Vegas</City>
			<State>NV</State>
			<Zip>89109</Zip>
		</Address>
	</Hotel>
	<Hotel>
		<Name>Omni Tucson National Resort &amp; Spa</Name>
		<Phone>520-297-2271</Phone>
		<Address NearstAirport="Tucson International Airport">
			<Number>2727</Number>
			<Street>W Club Dr</Street>
			<City>Tucson</City>
			<State>AZ</State>
			<Zip>85742</Zip>
		</Address>
	</Hotel>
</Hotels>
